// Thin `invoke` wrapper. Inside the Tauri webview it delegates to the real
// `@tauri-apps/api` IPC. In a plain browser (`bun run dev`) there is no backend,
// so it serves static JSON fixtures captured from the real commands run against
// `testdata` — letting every view render and be screenshotted without Tauri.
//
// The fixtures are loaded lazily via dynamic import: they are code-split into
// their own chunk and never enter the Tauri entry bundle (where `isTauri` is
// true and the real IPC is used).
//
// Regenerate the fixtures with:
//   cargo test gen_dev_fixtures -- --ignored   (in app/src-tauri)

import { invoke as tauriInvoke } from "@tauri-apps/api/core";
import type { InvokeArgs } from "@tauri-apps/api/core";
import { isTauri, isWeb } from "./caps";
import type {
  ChildResult,
  ParentsResult,
  ReversePair,
  SaveSummary,
  SpeciesDetail,
  SpeciesEntry,
} from "./types";

interface DevFixtures {
  /** Command name -> whole fixture, for commands with no argument keying. */
  simple: Record<string, unknown>;
  /** Species detail keyed by internal id. */
  detail: Record<string, SpeciesDetail>;
  /** Parent pairs keyed by child internal id. */
  parents: Record<string, ParentsResult>;
  /** Reverse breeding parent pairs keyed by child internal id. */
  reverse: Record<string, ReversePair[]>;
  /** Child keyed by canonical "min_id|max_id" of the two parents. */
  child: Record<string, { id: string; name: string; paldex_no: number }>;
  /** Full species list, for synthesizing detail of uncovered ids. */
  species: SpeciesEntry[];
}

let devPromise: Promise<DevFixtures> | null = null;

// The active-skills fixture (`active-skills.json`) is generated by the WazaData
// slice and may not exist yet (it lands mid-flight and is announced on IRC). A
// glob with a zero-match pattern compiles to an empty map, so a missing file
// degrades to `{}` (the humanizer fallback in `lib/active-skills.ts` then takes
// over) instead of breaking the dev build.
const activeSkillsGlob = import.meta.glob<Record<string, unknown>>(
  "../dev-fixtures/active-skills.json",
  { import: "default" },
);

/** Load and cache the dev fixtures on first browser-mode invoke. */
function loadDev(): Promise<DevFixtures> {
  if (!devPromise) {
    devPromise = Promise.all([
      import("../dev-fixtures/paldex-species.json"),
      import("../dev-fixtures/roster-counts.json"),
      import("../dev-fixtures/save-summary.json"),
      import("../dev-fixtures/solve-result.json"),
      import("../dev-fixtures/solve-queue.json"),
      import("../dev-fixtures/list-passives.json"),
      import("../dev-fixtures/paldex-species-detail.json"),
      import("../dev-fixtures/breeding-parents.json"),
      import("../dev-fixtures/reverse-breeding.json"),
      import("../dev-fixtures/breeding-child.json"),
      import("../dev-fixtures/breeding-boosts.json"),
      import("../dev-fixtures/lab-research.json"),
      import("../dev-fixtures/map-state.json"),
    ]).then(([species, roster, save, solve, solveQueue, passives, detail, parents, reverse, child, boosts, labResearch, mapState]) => {
      const speciesData = species.default as unknown as SpeciesEntry[];
      return {
        simple: {
          load_save: save.default,
          solve: solve.default,
          solve_queue: solveQueue.default,
          list_species: speciesData.map((s) => ({ id: s.id, name: s.name })),
          list_passives: passives.default,
          list_breeding_boosts: boosts.default,
          list_lab_research: labResearch.default,
          // Co-op reference world: egg incubation scanned as 1h so the setup
          // panel's "scanned from world" hatch state renders in browser dev.
          get_world_options: { egg_hatch_hours: 1 },
          paldex_species: speciesData,
          roster_counts: roster.default,
          get_map_state: mapState.default,
        },
        detail: detail.default as unknown as Record<string, SpeciesDetail>,
        parents: parents.default as Record<string, ParentsResult>,
        reverse: reverse.default as Record<string, ReversePair[]>,
        child: child.default as DevFixtures["child"],
        species: speciesData,
      };
    });
  }
  return devPromise;
}

/** Canonical "min_id|max_id" key matching the child-fixture generator. */
function pairKey(a: string, b: string): string {
  return a <= b ? `${a}|${b}` : `${b}|${a}`;
}

function arg(args: InvokeArgs | undefined, key: string): string {
  return String((args as Record<string, unknown> | undefined)?.[key] ?? "");
}

// ------------------------------------------------------------------ *
// Dev-mode progress simulation (fixture mode only).
//
// Real mode streams `solve-progress` events from Rust while a solve runs; the
// fixture shim has no backend and resolves instantly. To keep the in-flight
// progress panel reviewable in `bun run dev`, fixture mode synthesizes a
// realistic event sequence (seeding -> steps 1..3 -> finalizing) over ~3s and
// delays the fixture resolve until it finishes. `use-solve` subscribes via
// `listenProgress` (mirroring the Tauri `listen("solve-progress")` it uses
// in real mode); `cancel_solve` interrupts the sequence with a "cancelled"
// throw, matching the backend's `Err("cancelled")` resolution.
// ------------------------------------------------------------------ */

/** A subscriber to `solve-progress` payloads on the non-Tauri progress bus (fed
 *  by the fixture simulator below and, in web mode, by the wasm worker). */
type ProgressListener = (payload: Record<string, unknown>) => void;

const progressListeners = new Set<ProgressListener>();
const devCancelled = new Set<number>();

/** Subscribe to progress on the non-Tauri bus — the browser analogue of
 *  `listen("solve-progress", …)`. Both fixture mode (the simulator) and web mode
 *  (the worker) push here, so `use-solve` takes one path for both. Returns an
 *  unlisten fn. */
export function listenProgress(cb: ProgressListener): () => void {
  progressListeners.add(cb);
  return () => {
    progressListeners.delete(cb);
  };
}

/** Fan a progress payload out to every subscriber. */
function emitProgress(payload: Record<string, unknown>): void {
  for (const cb of progressListeners) cb(payload);
}

const devSleep = (ms: number): Promise<void> => {
  const { promise, resolve } = Promise.withResolvers<void>();
  setTimeout(resolve, ms);
  return promise;
};

/** Play a realistic seeding -> steps 1..3 -> finalizing sequence for `token`
 *  over ~3s, emitting `solve-progress`-shaped payloads to every subscriber and
 *  honoring a mid-flight `cancel_solve`. Throws `Error("cancelled")` when the
 *  matching token was cancelled, so the awaiting solve rejects like real mode. */
async function devSimulateProgress(
  token: number,
  queue?: { index: number; len: number },
): Promise<void> {
  const start = performance.now();
  const kind = queue ? "queue" : "single";
  const queueMeta = queue
    ? { queue_index: queue.index, queue_len: queue.len }
    : {};
  const maxSteps = 3;
  const stepTotals = [820_000, 2_400_000, 3_600_000];
  const stepWorkingSet = [1_200, 5_400, 14_800];

  const bail = () => {
    if (devCancelled.has(token)) throw new Error("cancelled");
  };
  const emit = (fields: Record<string, unknown>) => {
    bail();
    const payload = {
      token,
      kind,
      ...queueMeta,
      max_steps: maxSteps,
      elapsed_ms: Math.round(performance.now() - start),
      ...fields,
    };
    emitProgress(payload);
  };

  emit({ phase: "seeding", step: 0, pairs_done: 0, pairs_total: 0, working_set: 0 });
  await devSleep(500);
  bail();

  for (let s = 0; s < maxSteps; s++) {
    const total = stepTotals[s];
    for (let frame = 1; frame <= 5; frame++) {
      emit({
        phase: "step",
        step: s + 1,
        pairs_done: Math.round((total * frame) / 5),
        pairs_total: total,
        working_set: stepWorkingSet[s],
      });
      await devSleep(160);
      bail();
    }
  }

  emit({
    phase: "finalizing",
    step: maxSteps,
    pairs_done: 0,
    pairs_total: 0,
    working_set: stepWorkingSet[maxSteps - 1],
  });
  await devSleep(350);
  bail();
}

/** Serve a command from the dev fixtures, with graceful fallbacks. */
async function invokeDev<T>(cmd: string, args?: InvokeArgs): Promise<T> {
  const dev = await loadDev();

  // Cancel a simulated solve: flag the token so the running sequence bails.
  if (cmd === "cancel_solve") {
    const token = Number((args as Record<string, unknown> | undefined)?.token);
    if (Number.isFinite(token)) devCancelled.add(token);
    return undefined as T;
  }

  // Solves carry a `progress_token` when the caller wants events. In fixture
  // mode there is no backend to emit them, so drive the simulated sequence here
  // (and delay the fixture resolve behind it) before returning the static plan.
  if (cmd === "solve" || cmd === "solve_queue") {
    const raw = args as Record<string, unknown> | undefined;
    const spec = raw?.spec as Record<string, unknown> | undefined;
    const items = raw?.items as Record<string, unknown>[] | undefined;
    const token =
      cmd === "solve" ? spec?.progress_token : items?.[0]?.progress_token;
    if (typeof token === "number") {
      try {
        if (cmd === "solve") {
          await devSimulateProgress(token);
        } else {
          const len = items?.length ?? 0;
          for (let i = 0; i < len; i++) {
            await devSimulateProgress(token, { index: i, len });
          }
        }
      } finally {
        devCancelled.delete(token);
      }
    }
    return dev.simple[cmd] as T;
  }

  if (cmd === "paldex_species_detail") {
    const id = arg(args, "id");
    const hit = dev.detail[id];
    if (hit) return hit as T;
    // Synthesize a minimal detail (header/stats/passives) for uncovered ids so
    // in-dex navigation never hard-errors; breeding panels read as empty.
    const row = dev.species.find((s) => s.id === id);
    if (row) {
      return { ...row, breeding: { parent_pair_count: 0, unique_combos: [] } } as T;
    }
    throw new Error(`dev shim: unknown pal '${id}'`);
  }

  if (cmd === "breeding_parents") {
    const child = arg(args, "child");
    return (dev.parents[child] ?? { total: 0, pairs: [] }) as T;
  }

  if (cmd === "reverse_breeding") {
    const species = arg(args, "species");
    return (dev.reverse[species] ?? []) as T;
  }

  if (cmd === "breeding_child") {
    const a = arg(args, "parentA");
    const b = arg(args, "parentB");
    const child = dev.child[pairKey(a, b)] ?? null;
    return { child } as ChildResult as T;
  }

  if (cmd === "list_active_skills") {
    const loader = activeSkillsGlob["../dev-fixtures/active-skills.json"];
    return (loader ? await loader() : {}) as T;
  }

  if (cmd in dev.simple) return dev.simple[cmd] as T;

  throw new Error(
    `dev shim: no fixture for command '${cmd}' (run in Tauri, or add a fixture)`,
  );
}

// ---------------- Web mode: wasm-worker RPC client ----------------- *
// In the static browser build (VITE_BACKEND=web) every command runs in a Web
// Worker hosting the pal-web wasm (./worker.ts). Requests are correlated by a
// monotonic id; solve progress arrives out-of-band as `{ progress }` and is
// fanned onto the shared non-Tauri bus (emitProgress), so use-solve's browser
// progress path serves web and fixture alike.

interface WorkerResponseOk {
  id: number;
  ok: true;
  value: unknown;
}
interface WorkerResponseErr {
  id: number;
  ok: false;
  error: string;
}
interface WorkerProgressMsg {
  progress: Record<string, unknown>;
}
type WorkerMessage = WorkerResponseOk | WorkerResponseErr | WorkerProgressMsg;

interface PendingRequest {
  resolve: (value: unknown) => void;
  reject: (error: Error) => void;
}

let worker: Worker | null = null;
let nextReqId = 1;
const pending = new Map<number, PendingRequest>();

/** Lazily spawn the singleton worker. Built as its own chunk (via `new URL`),
 *  so the wasm stays out of the desktop entry bundle — fetched only on first
 *  call, which never happens outside web mode. */
function getWorker(): Worker {
  if (worker) return worker;
  const w = new Worker(new URL("./worker.ts", import.meta.url), {
    type: "module",
  });
  w.onmessage = (e: MessageEvent<WorkerMessage>) => {
    const msg = e.data;
    if ("progress" in msg) {
      emitProgress(msg.progress);
      return;
    }
    const req = pending.get(msg.id);
    if (!req) return;
    pending.delete(msg.id);
    if (msg.ok) req.resolve(msg.value);
    else req.reject(new Error(msg.error));
  };
  w.onerror = (e) => {
    // A worker-level failure (e.g. wasm instantiation) would otherwise hang every
    // in-flight request forever; reject them all so callers surface the error.
    const err = new Error(e.message || "worker error");
    for (const req of pending.values()) req.reject(err);
    pending.clear();
  };
  worker = w;
  return w;
}

/** Post an RPC to the worker and resolve with its response value. */
function postToWorker<T>(
  cmd: string,
  args: unknown,
  transfer?: Transferable[],
): Promise<T> {
  const id = nextReqId++;
  const { promise, resolve, reject } = Promise.withResolvers<unknown>();
  pending.set(id, { resolve, reject });
  getWorker().postMessage({ id, cmd, args }, transfer ?? []);
  return promise as Promise<T>;
}

/** Serve a command from the wasm worker (web mode). */
function invokeWeb<T>(cmd: string, args?: InvokeArgs): Promise<T> {
  return postToWorker<T>(cmd, args ?? {});
}

/** Web mode only: hand the freshly-read save bundle to the worker (the byte
 *  buffers move via transfer) to cache + summarize it. Returns the SaveSummary,
 *  identical in shape to the native `load_save`. */
export function loadSaveBundle(
  paths: string[],
  buffers: ArrayBuffer[],
): Promise<SaveSummary> {
  return postToWorker<SaveSummary>("__load_bundle", { paths, buffers }, buffers);
}

/** One logical save file within a WGS world and the on-disk blob backing it.
 *  Snake_case to match the Rust `WgsFileDto` JSON. */
export interface WgsFileRef {
  /** Bundle-relative role path: `"Level.sav"`, `"Players/<UID>.sav"`, … */
  target_path: string;
  /** Store-root-relative on-disk path `"<CONTAINER_DIR_HEX>/<BLOB_HEX>"`. */
  blob_path: string;
  size: number;
}

/** One world (save slot) resolved from a WGS store index. */
export interface WgsWorldManifest {
  save_id: string;
  /** Max FILETIME (100ns ticks) across the world's containers. */
  mtime_ticks: number;
  files: WgsFileRef[];
}

/** A parsed WGS store: every world plus non-fatal skip warnings. */
export interface WgsManifest {
  worlds: WgsWorldManifest[];
  warnings: string[];
}

/** Web mode only: parse a dropped WGS store into a manifest. `paths` + `buffers`
 *  are the `containers.index` + every `container.<N>` file (store-root-relative,
 *  tiny metadata — copied, not transferred, so the caller may keep reading the
 *  source). `presentPaths` is every store-relative file path in the store: the
 *  manifest core probes blob existence through them (no bytes read), so a world's
 *  Level/player blobs aren't dropped as missing. */
export function wgsManifest(
  paths: string[],
  buffers: ArrayBuffer[],
  presentPaths: string[],
): Promise<WgsManifest> {
  return postToWorker<WgsManifest>("__wgs_manifest", { paths, buffers, presentPaths });
}

/** Web mode only: decompress a `LevelMeta.sav` blob and return its world name,
 *  or null when absent/corrupt/unnamed. Used to label the world picker. */
export function wgsWorldName(levelMeta: ArrayBuffer): Promise<string | null> {
  return postToWorker<string | null>("__wgs_world_name", { blob: levelMeta });
}

/**
 * Invoke a Tauri command. Three backends by mode: the real IPC inside Tauri,
 * the wasm worker in the web build (VITE_BACKEND=web), and static fixtures in a
 * plain browser. Fixture mode throws for commands without a fixture so dev gaps
 * are obvious rather than silently wrong.
 */
export function invoke<T>(cmd: string, args?: InvokeArgs): Promise<T> {
  if (isTauri) return tauriInvoke<T>(cmd, args);
  if (isWeb) return invokeWeb<T>(cmd, args);
  return invokeDev<T>(cmd, args);
}
