// Thin `invoke` wrapper. Inside the Tauri webview it delegates to the real
// `@tauri-apps/api` IPC. In a plain browser (`bun run dev`) there is no backend,
// so it serves static JSON fixtures captured from the real commands run against
// `testdata` — letting every view render and be screenshotted without Tauri.
//
// The fixtures are loaded lazily via dynamic import: they are code-split into
// their own chunk and never enter the Tauri entry bundle (where `isTauri` is
// true and the real IPC is used).
//
// Regenerate the fixtures with:
//   cargo test gen_dev_fixtures -- --ignored   (in app/src-tauri)

import { invoke as tauriInvoke } from "@tauri-apps/api/core";
import type { InvokeArgs } from "@tauri-apps/api/core";
import type {
  ChildResult,
  ParentsResult,
  SpeciesDetail,
  SpeciesEntry,
} from "./types";

/** Tauri v2 injects this global into the webview; absent in a plain browser. */
const isTauri = typeof window !== "undefined" && "__TAURI_INTERNALS__" in window;

interface DevFixtures {
  /** Command name -> whole fixture, for commands with no argument keying. */
  simple: Record<string, unknown>;
  /** Species detail keyed by internal id. */
  detail: Record<string, SpeciesDetail>;
  /** Parent pairs keyed by child internal id. */
  parents: Record<string, ParentsResult>;
  /** Child keyed by canonical "min_id|max_id" of the two parents. */
  child: Record<string, { id: string; name: string; paldex_no: number }>;
  /** Full species list, for synthesizing detail of uncovered ids. */
  species: SpeciesEntry[];
}

let devPromise: Promise<DevFixtures> | null = null;

// The active-skills fixture (`active-skills.json`) is generated by the WazaData
// slice and may not exist yet (it lands mid-flight and is announced on IRC). A
// glob with a zero-match pattern compiles to an empty map, so a missing file
// degrades to `{}` (the humanizer fallback in `lib/active-skills.ts` then takes
// over) instead of breaking the dev build.
const activeSkillsGlob = import.meta.glob<Record<string, unknown>>(
  "../dev-fixtures/active-skills.json",
  { import: "default" },
);

/** Load and cache the dev fixtures on first browser-mode invoke. */
function loadDev(): Promise<DevFixtures> {
  if (!devPromise) {
    devPromise = Promise.all([
      import("../dev-fixtures/paldex-species.json"),
      import("../dev-fixtures/roster-counts.json"),
      import("../dev-fixtures/save-summary.json"),
      import("../dev-fixtures/solve-result.json"),
      import("../dev-fixtures/solve-queue.json"),
      import("../dev-fixtures/list-passives.json"),
      import("../dev-fixtures/paldex-species-detail.json"),
      import("../dev-fixtures/breeding-parents.json"),
      import("../dev-fixtures/breeding-child.json"),
      import("../dev-fixtures/breeding-boosts.json"),
      import("../dev-fixtures/lab-research.json"),
    ]).then(([species, roster, save, solve, solveQueue, passives, detail, parents, child, boosts, labResearch]) => {
      const speciesData = species.default as unknown as SpeciesEntry[];
      return {
        simple: {
          load_save: save.default,
          solve: solve.default,
          solve_queue: solveQueue.default,
          list_species: speciesData.map((s) => ({ id: s.id, name: s.name })),
          list_passives: passives.default,
          list_breeding_boosts: boosts.default,
          list_lab_research: labResearch.default,
          // Co-op reference world: egg incubation scanned as 1h so the setup
          // panel's "scanned from world" hatch state renders in browser dev.
          get_world_options: { egg_hatch_hours: 1 },
          paldex_species: speciesData,
          roster_counts: roster.default,
        },
        detail: detail.default as unknown as Record<string, SpeciesDetail>,
        parents: parents.default as Record<string, ParentsResult>,
        child: child.default as DevFixtures["child"],
        species: speciesData,
      };
    });
  }
  return devPromise;
}

/** Canonical "min_id|max_id" key matching the child-fixture generator. */
function pairKey(a: string, b: string): string {
  return a <= b ? `${a}|${b}` : `${b}|${a}`;
}

function arg(args: InvokeArgs | undefined, key: string): string {
  return String((args as Record<string, unknown> | undefined)?.[key] ?? "");
}

// ------------------------------------------------------------------ *
// Dev-mode progress simulation (fixture mode only).
//
// Real mode streams `solve-progress` events from Rust while a solve runs; the
// fixture shim has no backend and resolves instantly. To keep the in-flight
// progress panel reviewable in `bun run dev`, fixture mode synthesizes a
// realistic event sequence (seeding -> steps 1..3 -> finalizing) over ~3s and
// delays the fixture resolve until it finishes. `use-solve` subscribes via
// `devListenProgress` (mirroring the Tauri `listen("solve-progress")` it uses
// in real mode); `cancel_solve` interrupts the sequence with a "cancelled"
// throw, matching the backend's `Err("cancelled")` resolution.
// ------------------------------------------------------------------ */

/** A subscriber to simulated `solve-progress` payloads (fixture mode only). */
type DevProgressListener = (payload: Record<string, unknown>) => void;

const devProgressListeners = new Set<DevProgressListener>();
const devCancelled = new Set<number>();

/** True in a plain browser (`bun run dev`): no Tauri backend, fixtures serve.
 *  Gates the dev-only progress simulator so real mode is never affected. */
export function isFixtureMode(): boolean {
  return !isTauri;
}

/** Subscribe to simulated progress in fixture mode — the fixture-mode analogue
 *  of `listen("solve-progress", …)`. Returns an unlisten fn. */
export function devListenProgress(cb: DevProgressListener): () => void {
  devProgressListeners.add(cb);
  return () => {
    devProgressListeners.delete(cb);
  };
}

const devSleep = (ms: number): Promise<void> => {
  const { promise, resolve } = Promise.withResolvers<void>();
  setTimeout(resolve, ms);
  return promise;
};

/** Play a realistic seeding -> steps 1..3 -> finalizing sequence for `token`
 *  over ~3s, emitting `solve-progress`-shaped payloads to every subscriber and
 *  honoring a mid-flight `cancel_solve`. Throws `Error("cancelled")` when the
 *  matching token was cancelled, so the awaiting solve rejects like real mode. */
async function devSimulateProgress(
  token: number,
  queue?: { index: number; len: number },
): Promise<void> {
  const start = performance.now();
  const kind = queue ? "queue" : "single";
  const queueMeta = queue
    ? { queue_index: queue.index, queue_len: queue.len }
    : {};
  const maxSteps = 3;
  const stepTotals = [820_000, 2_400_000, 3_600_000];
  const stepWorkingSet = [1_200, 5_400, 14_800];

  const bail = () => {
    if (devCancelled.has(token)) throw new Error("cancelled");
  };
  const emit = (fields: Record<string, unknown>) => {
    bail();
    const payload = {
      token,
      kind,
      ...queueMeta,
      max_steps: maxSteps,
      elapsed_ms: Math.round(performance.now() - start),
      ...fields,
    };
    for (const cb of devProgressListeners) cb(payload);
  };

  emit({ phase: "seeding", step: 0, pairs_done: 0, pairs_total: 0, working_set: 0 });
  await devSleep(500);
  bail();

  for (let s = 0; s < maxSteps; s++) {
    const total = stepTotals[s];
    for (let frame = 1; frame <= 5; frame++) {
      emit({
        phase: "step",
        step: s + 1,
        pairs_done: Math.round((total * frame) / 5),
        pairs_total: total,
        working_set: stepWorkingSet[s],
      });
      await devSleep(160);
      bail();
    }
  }

  emit({
    phase: "finalizing",
    step: maxSteps,
    pairs_done: 0,
    pairs_total: 0,
    working_set: stepWorkingSet[maxSteps - 1],
  });
  await devSleep(350);
  bail();
}

/** Serve a command from the dev fixtures, with graceful fallbacks. */
async function invokeDev<T>(cmd: string, args?: InvokeArgs): Promise<T> {
  const dev = await loadDev();

  // Cancel a simulated solve: flag the token so the running sequence bails.
  if (cmd === "cancel_solve") {
    const token = Number((args as Record<string, unknown> | undefined)?.token);
    if (Number.isFinite(token)) devCancelled.add(token);
    return undefined as T;
  }

  // Solves carry a `progress_token` when the caller wants events. In fixture
  // mode there is no backend to emit them, so drive the simulated sequence here
  // (and delay the fixture resolve behind it) before returning the static plan.
  if (cmd === "solve" || cmd === "solve_queue") {
    const raw = args as Record<string, unknown> | undefined;
    const spec = raw?.spec as Record<string, unknown> | undefined;
    const items = raw?.items as Record<string, unknown>[] | undefined;
    const token =
      cmd === "solve" ? spec?.progress_token : items?.[0]?.progress_token;
    if (typeof token === "number") {
      try {
        if (cmd === "solve") {
          await devSimulateProgress(token);
        } else {
          const len = items?.length ?? 0;
          for (let i = 0; i < len; i++) {
            await devSimulateProgress(token, { index: i, len });
          }
        }
      } finally {
        devCancelled.delete(token);
      }
    }
    return dev.simple[cmd] as T;
  }

  if (cmd === "paldex_species_detail") {
    const id = arg(args, "id");
    const hit = dev.detail[id];
    if (hit) return hit as T;
    // Synthesize a minimal detail (header/stats/passives) for uncovered ids so
    // in-dex navigation never hard-errors; breeding panels read as empty.
    const row = dev.species.find((s) => s.id === id);
    if (row) {
      return { ...row, breeding: { parent_pair_count: 0, unique_combos: [] } } as T;
    }
    throw new Error(`dev shim: unknown pal '${id}'`);
  }

  if (cmd === "breeding_parents") {
    const child = arg(args, "child");
    return (dev.parents[child] ?? { total: 0, pairs: [] }) as T;
  }

  if (cmd === "breeding_child") {
    const a = arg(args, "parentA");
    const b = arg(args, "parentB");
    const child = dev.child[pairKey(a, b)] ?? null;
    return { child } as ChildResult as T;
  }

  if (cmd === "list_active_skills") {
    const loader = activeSkillsGlob["../dev-fixtures/active-skills.json"];
    return (loader ? await loader() : {}) as T;
  }

  if (cmd in dev.simple) return dev.simple[cmd] as T;

  throw new Error(
    `dev shim: no fixture for command '${cmd}' (run in Tauri, or add a fixture)`,
  );
}

/**
 * Invoke a Tauri command. Delegates to the real IPC inside Tauri; serves a
 * static fixture in a plain browser. Throws for commands without a fixture so
 * dev gaps are obvious rather than silently wrong.
 */
export function invoke<T>(cmd: string, args?: InvokeArgs): Promise<T> {
  if (isTauri) {
    return tauriInvoke<T>(cmd, args);
  }
  return invokeDev<T>(cmd, args);
}
